src/objects/Timesheet__c.object
<CustomObject>
    <fields>
        <fullName>Employee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employee</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Timesheets</relationshipLabel>
        <relationshipName>Timesheets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Timesheet</label>
    <nameField>
        <displayFormat>TS-{YY}{MM}{000}</displayFormat>
        <label>Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Timesheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TimesheetController.cls
public with sharing class TimesheetController 
{
    private final Timesheet__c ts;
    private boolean isEdit = false;
    ApexPages.StandardController std;

    public TimesheetController(ApexPages.StandardController stdController) 
    {
    	this.std = stdController;
        this.ts = (Timesheet__c)stdController.getRecord();
        this.isEdit = true;
    }

    public Boolean getIsEdit() {
        return isEdit;
    }
    
    public void edit() {
        isEdit=true;
    }    
    
    public void cancel() 
    {
        isEdit=false;
    }
    
    public void save ()
    {
    	ID userContactId = [select ContactID from User where ID = :UserInfo.getUserId()].ContactID;
 		if (ts.Employee__c == null) ts.Employee__c = userContactId; 
        isEdit=false;
    	std.save();
    }
}